# -*- coding: utf-8 -*-
PAGE = dict(
  slug="is-lyon-safe-for-jewish-visitors",
  title="Is Lyon safe for Jewish visitors? Our standard",
  desc="How Mishpacha Tours secures its private Jewish tours of Lyon: discreet routes, a guide from the community, security escort on request. The sourced facts.",
  h1="Is Lyon safe for Jewish visitors?", ital="a straight answer, and what we do about it",
  intro="Most Jewish visits to Lyon pass without incident, and every Mishpacha Tours visit is run as a secured tour: a private group, discreet routes and meeting points fixed in advance, a guide who belongs to the community, and a professional security escort on request. Antisemitic acts do occur in the Lyon area, so we give you the figures and the practical steps below, without alarm and without spin.",
  chips=["Private groups only", "Discreet routes, fixed in advance", "Security escort on request", "Checked 7 October 2026"],
  illus="line-doorway.png",
  crumb=("../jewish-lyon-guide/", "Jewish Lyon guide"),
  sections=[
    dict(type="text", h2="What we do on <i>every tour</i>",
      html="<ul><li><b>Your group only.</b> We never join you to strangers. One guide, one group, from one to ten people.</li><li><b>Routes and meeting points fixed in advance.</b> We choose them before you arrive, we send them to you alone, and we do not publish them. Your guide adapts the route on the day if a street or a square is better avoided.</li><li><b>A guide from the community.</b> She knows which doors open, who to call, and how the city feels that week. She is in contact with the community institutions you visit.</li><li><b>A professional security escort on request.</b> A security agent can accompany any tour. The escort is priced separately, on quote, and is never included in the tour price. We work with professional security agents regularly for community events in Lyon.</li><li><b>No tours on Shabbat or Jewish holidays.</b> Friday tours end early enough for you to be back well before candle lighting.</li></ul>"),
    dict(type="beige", h2="Synagogues and <i>public protection</i>",
      html="<p>French authorities keep security forces visible around synagogues and Jewish schools. A national instruction of the Interior Ministry, reported by the press in late August 2026, asks for visible forces and possible checks around synagogues. At the Grande Synagogue and at Neveh Shalom, entry depends on the opening hours and the security clearance of the day: bring a photo ID and expect a bag check at the door. If entry is refused on the day, the tour goes on outside and the price does not change.</p>"),
    dict(type="text", h2="The facts, <i>sourced</i>",
      html="<p>Lyon Capitale counted 36 antisemitic acts in the Lyon area between 7 October and 1 November 2023, with five arrests. The Rhône prefecture said at the time that patrols and the Sentinelle military mission were reinforced in front of Jewish institutions. We publish no other figure that we have not checked ourselves, and we promise no zero risk. What we promise is the standard above, on every tour.</p>"),
    dict(type="text", h2="Common sense <i>on the road</i>",
      html="<ul><li>Keep your plans within your group. Do not post your route, your hotel or your synagogue in real time.</li><li>Walk with a companion rather than alone at night, as in any large city.</li><li>Whether you wear a kippah or a hat in the street is your decision. Tell your guide what you prefer and she plans the walk accordingly.</li><li>Carry a photo ID: synagogues and memorials ask for it at the door.</li><li>Save the WhatsApp number of your guide before the tour. She answers the same day, never on Shabbat.</li></ul>"),
    dict(type="faq", h2="Security: <i>your questions</i>", items=[
      ("Is the security escort included in the price?", "No. A professional security escort is available on request, on any tour, and is quoted separately. Ask for it when you book."),
      ("Do we need to show ID?", "Yes. The Grande Synagogue, Neveh Shalom and the memorials ask for a photo ID at the door, and a bag check is normal."),
      ("What happens if the synagogue refuses entry on the day?", "The tour goes on outside, your guide tells the story from the quai, and the price does not change. Entry always depends on the opening hours and the security clearance of the day."),
      ("Do you run tours on Shabbat or Jewish holidays?", "No. We run Sunday to Friday morning. Friday tours end early enough for you to be home well before candle lighting."),
      ("Can we visit as a large family?", "Yes, up to ten people on one booking. Larger groups are split or quoted separately, and the escort is advised for them."),
    ]),
    dict(type="cta", txt="Want a secured tour with an escort?", msg="Hello, I would like a quote for a tour with a security escort. Dates: / Number of people: / Preferred language:"),
  ],
  related=[("../jewish-travel-lyon-faq/", "Jewish travel to Lyon: the honest FAQ"), ("../grande-synagogue-lyon/", "The Grande Synagogue of Lyon"), ("../tours/jewish-lyon/", "Jewish Lyon tour, 2h30"), ("../synagogues-lyon/", "Synagogues in Lyon")],
  source="Sources: Lyon Capitale (November 2023), statements of the Préfecture du Rhône reported in the press (November 2023), national press on the Interior Ministry instruction (late August 2026), our booking terms.",
  jsonld=None, ticket=True,
  VERIF=[
    "36 antisemitic acts and five arrests (7 October to 1 November 2023): Lyon Capitale, as already quoted on /jewish-travel-lyon-faq/. Figure to refresh if a newer local count is published.",
    "'We work with professional security agents regularly for community events in Lyon': operator statement of 10/08/2026 (ETAT), capacity confirmed, no contract quoted.",
    "Interior Ministry instruction of late August 2026: national press, as on the FAQ page. No circular number quoted.",
    "'Larger groups are split or quoted separately': follows the ten-person ceiling of the price grid; to confirm with the operator.",
    "Kippah or hat: our own advice, no official recommendation quoted.",
  ],
)
