# -*- coding: utf-8 -*-
PAGE = dict(
  slug="jewish-travel-lyon-faq",
  title="Jewish travel to Lyon: the honest FAQ",
  desc="Nineteen straight answers for a Jewish traveller to Lyon: getting there, kosher, Shabbat, security, prayer and our private tours. Checked 7 October 2026.",
  h1="Jewish travel to Lyon", ital="the honest FAQ",
  intro="You want facts before you book. Below are the questions Jewish travellers ask us about Lyon, answered with what we can source and clear about what is not published. Security gets a direct answer, without alarm and without spin.",
  chips=["19 questions", "4 sections", "Sourced, with gaps marked", "Checked 7 October 2026"],
  illus="line-whatsapp.png",
  crumb=("../jewish-lyon-guide/", "Jewish Lyon guide"),
  sections=[
    dict(type="faq", h2="Getting there <i>and around</i>", items=[
      ("How do I get from Lyon-Saint-Exupéry airport to the city?", "Take the Rhônexpress. It links the airport and Lyon Part-Dieu (stop Part-Dieu Vivier Merle) in less than 30 minutes, every 15 minutes, from 4:25 to midnight, seven days a week. Tickets are sold on rhonexpress.fr. The airport also has its own train station."),
      ("How do I get from Part-Dieu to the old town?", "Lyon Part-Dieu is the city's main station. The TCL metro and tram network (tcl.fr) runs from there to Bellecour and Vieux Lyon. On a weekday, ask us your route when you book and we write it for you."),
      ("Can I take a taxi or the metro on Friday evening?", "Plan your transfers before candle lighting. Once Shabbat starts, the metro and taxis are off the table if you keep Shabbat. Book your airport transfer for Friday morning at the latest, and arrive at your hotel with time to spare."),
      ("Can I walk between the synagogue, the old town and the Presqu'île?", "Yes. The Grande Synagogue on quai Tilsitt is a short walk from Vieux Lyon and about ten minutes on foot from Bellecour, by our estimate. Villeurbanne is much farther: see <a href='../where-to-stay-lyon-jewish-travellers/'>where to stay in Lyon</a>."),
    ]),
    dict(type="photos", items=[("stock/boeuf-1.jpg", "Rue du Boeuf, Vieux Lyon"), ("stock/stecath-4.jpg", "Rue Sainte-Catherine"), ("stock/traboule-1.jpg", "A traboule"), ("stock/chrd-3.jpg", "The CHRD, Lyon")]),
    dict(type="faq", h2="Kosher, Shabbat <i>and community</i>", items=[
      ("Where can I eat kosher in Lyon?", "The Beth Din de Lyon certifies 36 places in Lyon, Villeurbanne and Écully: restaurants, bakeries, butchers, groceries and caterers. Most are in Villeurbanne and the 6th arrondissement. Vieux Lyon has none. See <a href='../kosher-restaurants-lyon/'>kosher restaurants in Lyon</a>."),
      ("Can I get a Shabbat meal?", "Yes, with advance notice. Order from a caterer certified by the Beth Din before Thursday, or ask a Chabad house for a meal. Delivery to hotels is not published: ask each caterer. See <a href='../kosher-shabbat-meals-catering-lyon/'>kosher catering and Shabbat meals</a>."),
      ("Is there a kosher hotel, and is there an eruv?", "We know of no kosher hotel in Lyon, and no public eruv is published for Lyon; plan accordingly. Our page <a href='../shabbat-in-lyon/'>Shabbat in Lyon</a> explains how to organise the weekend."),
      ("Where can I pray, and is there a minyan?", "The Grande Synagogue (Consistorial rite) and Neveh Chalom (Sephardi) hold services, and so do seven Chabad houses and 26 neighbourhood synagogues. Times are published for the two main synagogues only. See <a href='../synagogues-lyon/'>synagogues in Lyon</a>."),
      ("Is there a mikveh?", "Yes, several. Mikvah Haya Mouchka, 60 rue Crillon, is listed as open nightly. See <a href='../mikveh-lyon/'>mikveh in Lyon</a> for addresses and phones."),
      ("Where is the Jewish cemetery, and can I visit a family grave?", "The Jewish cemetery of Lyon is La Mouche, 11 rue Abraham-Bloch, open Sunday to Thursday 8:00 to 18:00 and Friday 8:00 to 16:00. Call the Consistoire first with the name of the person. See <a href='../jewish-cemetery-lyon/'>the cemetery page</a>."),
    ]),
    dict(type="faq", h2="Security: <i>a straight answer</i>", items=[
      ("Is Lyon safe for Jewish visitors?", "Most Jewish visits to Lyon pass without incident, but antisemitic acts do occur in the area: Lyon Capitale counted 36 between 7 October and 1 November 2023, with five arrests. The Rhône prefecture said at the time that patrols and the Sentinelle military mission were reinforced in front of Jewish institutions. Every Mishpacha Tours visit runs as a secured tour: private group, discreet routes, a guide from the community, a security escort on request. See <a href='../is-lyon-safe-for-jewish-visitors/'>our security standard</a>."),
      ("Are synagogues protected?", "Yes. French authorities keep security forces visible around synagogues and Jewish schools. A national instruction of the Interior Ministry reported by the press in late August 2026 asks for visible forces and possible checks around synagogues. Expect a check and bring a photo ID."),
      ("What common-sense steps do you advise?", "Keep your plans to yourself and your group, and do not post your route or your hotel in real time. Travel with a companion rather than alone at night. Choose your own level of visibility: some members of the Lyon community wear a cap rather than a kippa in public, according to Grand Rabbi Daniel Dahan (Lyon Capitale, November 2023). Tell us if you have concerns, and we adapt."),
      ("What does Mishpacha Tours do about security?", "Private groups only, never joined to strangers. Routes and meeting points chosen in advance and kept discreet. A guide who is a member of the community. A security escort on request, on any tour: it is priced separately and quoted on demand, never included in the tour price."),
    ]),
    dict(type="faq", h2="Our <i>tours</i>", items=[
      ("How much does a tour cost?", "The price is per group, not per person. The Jewish Lyon tour and the Memory tours cost 290 € for 1 to 4 people, plus 35 € per extra person from the 5th to the 10th. See <a href='../tours/jewish-lyon/'>the Jewish Lyon tour</a>."),
      ("In which languages do you guide?", "English, French or Spanish. We do not guide in Hebrew: Hebrew-speaking guests are guided in English. Tell us your language when you book."),
      ("Do you run tours on Shabbat?", "Never. We do not guide on Shabbat or on Jewish holidays. Sunday morning is possible, and so is a Friday morning tour that ends well before candle lighting."),
      ("Can I cancel?", "Yes, free of charge up to 24 hours before the start time."),
      ("Can we really go inside the Grande Synagogue?", "Yes, on the Jewish Lyon and Stopover tours. The synagogue is closed to visitors outside the Heritage Days, and entry depends on its opening hours and on security clearance on the day. Your guide confirms before the walk begins."),
    ]),
    dict(type="cta", txt="Have a question that is not here?", msg="Hello, I have a question about travelling to Lyon. Dates: / Number of people:"),
  ],
  related=[("../shabbat-in-lyon/", "Shabbat in Lyon"), ("../where-to-stay-lyon-jewish-travellers/", "Where to stay in Lyon"), ("../kosher-shabbat-meals-catering-lyon/", "Kosher catering and Shabbat meals"), ("../mikveh-lyon/", "Mikveh in Lyon"), ("../tours/jewish-lyon/", "Jewish Lyon tour, 2h30")],
  source="Sources: rhonexpress.fr, tcl.fr, bethdin-lyon.fr, consistoiredelyon.fr, nevehchalom.fr, mikvah.org, lyon.fr, lyoncapitale.fr (1 November 2023), connexionfrance.com (9 October 2023).",
  jsonld=None, ticket=True,
  VERIF=[
    "Rhônexpress (less than 30 min, every 15 min, 4:25 to midnight, Part-Dieu Vivier Merle, airport train station): rhonexpress.fr/en read on 7 October 2026. Fares not quoted.",
    "'Part-Dieu is the main station' and 'TCL runs from there to Bellecour and Vieux Lyon': general knowledge plus tcl.fr; the TCL page could not be opened (403). Line numbers deliberately not given.",
    "Friday taxi and metro advice: our advice for Shabbat keepers, no source.",
    "'About ten minutes from Bellecour': walking estimate from map coordinates, rounded to 5 minutes.",
    "'38 places certified': count of the published kosher page (all categories, 8 September 2026).",
    "Security: 36 acts and five arrests (Lyon Capitale, 1 November 2023, p=359917); patrols and Sentinelle reinforced (same article, Rhône prefecture). Grand Rabbi Daniel Dahan cap remark: same article. These are 2023 figures: the operator decides whether to keep the count in a public page.",
    "Late August 2026 Interior Ministry instruction: secondary press summary in the base factuelle of 8 September 2026 (section 2). Primary text not found.",
    "'Keep your plans to yourselves, do not post your route in real time, travel with a companion': our advice, no source.",
    "Security escort 'priced separately, quote on demand': ETAT.md decision of 08/09 and tour pages.",
    "Prices 290 EUR for 1 to 4 people, +35 EUR from the 5th to the 10th: launch grid, will become 350 EUR after 10 reviews or 3 months. Update this page then.",
    "Tilsitt entry on Stopover tour: ETAT.md decision of 08/09.",
    "Cemetery hours: lyon.fr via base factuelle 8 September 2026.",
    "Count of 'some thirty neighbourhood synagogues' and 'four Chabad houses': existing site pages (habadlyon.com, fr.chabad.org).",
  ],
)
