# -*- coding: utf-8 -*-
PAGE = dict(
  slug="kosher-services-french-alps",
  title="Kosher services in the French Alps: chef, minyan",
  desc="Chalet with a private chef, meals delivered to your group, Shabbat, holidays, minyan and Sefer Torah in the resort. Every kosher service in the French Alps, one request.",
  h1="Kosher services in the French Alps", ital="chalet, chef, meals, Shabbat, holidays, minyan: one request",
  intro="A kosher week in the mountains does not have to mean a suitcase of food from Lyon and a Shabbat alone. Mishpacha Tours organises it in the resorts of Isère, Savoie and the Hautes-Alpes, with its kosher team based in the Alps: a chalet with a private chef, meals for a group for the week, Shabbat and the holidays in the resort, a minyan and a Sefer Torah for your dates. Send us your resort, your dates and what you need. One contact, one answer, one quote.",
  chips=["Alpe d'Huez to Val Thorens", "Chef, delivered meals, Shabbat, holidays", "Minyan and Sefer Torah", "Checked 8 October 2026"],
  illus="flat-ski.png",
  crumb=("../jewish-lyon-guide/", "Jewish Lyon guide"),
  sections=[
    dict(type="text", h2="Every service, <i>one request</i>",
      html="<ul><li><b>A chalet with a private chef.</b> The team makes the kitchen kosher, the chef cooks on site, and every meal of the week is taken care of. You ski, you come back to a set table.</li><li><b>Meals delivered to your group.</b> Families, a group of friends, a yeshiva or synagogue group: hot meals delivered to your apartments or your hotel for the week, in the resort. Large groups welcome, with notice. Delivered meals are a community service of the Beth Habad de Grenoble Alpes, which prepares and delivers them.</li><li><b>Shabbat in the resort.</b> Shabbat meals, challot and wine delivered on Friday, and the nearest minyan for your dates.</li><li><b>The holidays in the mountains.</b> Hanukkah candles and a lighting, a Megillah reading and a Purim meal, Pesach on request. Say which holiday falls in your week.</li><li><b>A minyan and a Sefer Torah.</b> When several families are in the same resort, the team groups them for a minyan and brings a Sefer Torah, in winter and in summer. Give your dates early: the more families they know about, the easier the minyan.</li><li><b>A tailor-made short stay.</b> Chalet, chef, Shabbat, transfers to the slopes: the team puts the whole week together for one family or a few.</li></ul><p>Strictly kosher: our team in the Alps cooks under the Chabad network of the Alps. Ask for the details of supervision in writing with your quote, as you would anywhere.</p>"),
    dict(type="steps", h2="How it <i>works</i>", items=[
      ("Tell us", "Resort, dates, number of people, and the services you want: chalet with chef, delivered meals, Shabbat, a holiday, a minyan. By WhatsApp or with the form at the bottom of this page."),
      ("We put it together", "The same day, we check with our team in the Alps what is possible for your dates and your resort: chef, kitchen, deliveries, minyan. One contact from start to finish."),
      ("You get a quote", "The price depends on the resort, the dates, the number of people and the menu. You receive a written quote before you commit to anything."),
      ("Add Lyon if you land here", "Most families fly into Lyon. Our 3 hour <a href='../tours/stopover/'>Stopover</a> with the Grande Synagogue fits between the flight and the drive up."),
    ]),
    dict(type="beige", h2="Which resort, <i>which side</i>",
      html="<p>We cover the resorts on both sides of the mountains.</p><ul><li><b>The Grenoble side.</b> Alpe d'Huez, Les Deux Alpes, Chamrousse and Serre Chevalier, plus Val Thorens and Les Menuires in the Belleville valley: meals, chalets, Shabbat, holidays, minyan and Sefer Torah.</li><li><b>The Courchevel side.</b> Courchevel 1850 and Megève have a Chabad house in winter: we coordinate with it for your minyan and your Shabbat.</li></ul><p>Whatever the resort, one request to us. We know what is possible each week and we come back with one answer.</p>"),
    dict(type="map", h2="The resorts <i>on the map</i>", points=[
      ("Lyon-Saint-Exupéry airport", "Aéroport Lyon-Saint-Exupéry, 69125 Colombier-Saugnieu"),
      ("Grenoble, Beth Habad", "10 rue Lazare Carnot, 38000 Grenoble"),
      ("Chamrousse", "Chamrousse, 38410"),
      ("Alpe d'Huez", "Alpe d'Huez, 38750 Huez"),
      ("Les Deux Alpes", "Les Deux Alpes, 38860"),
      ("Serre Chevalier", "Serre Chevalier, 05240 La Salle-les-Alpes"),
      ("Val Thorens", "Val Thorens, 73440 Les Belleville"),
      ("Courchevel 1850", "Courchevel 1850, 73120 Saint-Bon-Tarentaise"),
      ("Megève", "Megève, 74120"),
    ], note="Town-level pins, not street addresses, except Grenoble.", h=440),
    dict(type="photos", items=[("stock/alpes-ski.jpg", "A piste above Megève"), ("stock/hallah.jpg", "Challot for Shabbat"), ("stock/alpes-montblanc.jpg", "The Mont Blanc massif from Megève"), ("stock/annecy-lac.jpg", "The lake of Annecy, on the way up")]),
    dict(type="faq", h2="Kosher services in the Alps: <i>questions</i>", items=[
      ("Is the food strictly kosher?", "Yes. Our team in the Alps cooks under the Chabad network of the Alps. Ask for the supervision details in writing with your quote."),
      ("Can we have kosher meals delivered to Val Thorens or Alpe d'Huez?", "Yes. The team delivers to a group for the week, in the resorts of the Grenoble side and in the Belleville valley. Send us the resort, the dates and the number of people."),
      ("Can we have a minyan and a Sefer Torah in the resort?", "Yes, when enough families are there at the same time. The team groups them and brings a Sefer Torah, in winter and in summer. The earlier they know your dates, the more likely the minyan."),
      ("What about Hanukkah, Purim or Pesach in the mountains?", "A lighting, a Megillah reading, a Purim meal, Pesach on request: tell us which holiday falls in your week and the team organises it in the resort."),
      ("Do you organise the chalet yourselves?", "Yes. Mishpacha Tours takes your request and organises it with its kosher team based in the Alps. You deal with one contact from start to finish."),
      ("How far ahead should we ask?", "As early as you can, and before the school holidays. A chef for a week is booked months ahead; delivered meals need less notice. A minyan is easier the earlier the team knows your dates."),
      ("What does it cost?", "No price list: a chalet with a chef for a week and a dozen meals delivered are not the same job. You receive a written quote before you commit to anything."),
    ]),
    dict(type="cta", txt="Kosher services in the Alps this season?", msg="Hello, we would like kosher services in the Alps. Resort: / Dates: / Number of people: / Services (chalet with chef, delivered meals, Shabbat, holiday, minyan):"),
  ],
  related=[("../kosher-ski-holidays-french-alps/", "Kosher ski holidays in the French Alps"), ("../lyon-gateway-to-the-alps-kosher/", "Lyon, the gateway to the Alps"), ("../tours/stopover/", "Stopover tour, 3 hours"), ("../summer-in-the-alps-jewish-families/", "Summer in the Alps for Jewish families"), ("../shabbat-in-lyon/", "Shabbat in Lyon")],
  source="Sources: our team in the Alps (8 October 2026), habadgrenoblealpes.com, synalpes.wordpress.com.",
  wa="33652092301",
  jsonld=None, ticket=True,
  VERIF=[
    "Whole offer (chalet with chef, delivered meals, Shabbat, holidays, minyan, Sefer Torah, tailor-made stays, large groups, resorts covered): two voice messages from Mendel Attal, Beth Habad de Grenoble Alpes, 8 October 2026, received by the operator. Nothing published. To confirm in writing with him before the first client.",
    "Presented as a Mishpacha Tours service, no partner name or number on the page (operator decision 08/10/2026: 'c'est un service de Mishpacha Tours'). Referral terms with Mendel Attal (20 percent of what his team invoices) not yet agreed in writing. Who invoices the client is still open: if Mishpacha Tours invoices a stay, Atout France registration applies.",
    "Supervision: 'under the Chabad network of the Alps' rests on Mendel's statement that the service belongs to the Beth Habad de Grenoble Alpes; no certificate seen. The page tells the client to ask in writing.",
    "Pesach 'on request' and 'transfers to the slopes' in a tailor-made stay: inferred from Mendel's 'mini séjour sur mesure, on s'occupe de tout', not stated as such. To confirm.",
    "Courchevel and Megève Chabad house: synalpes.wordpress.com, not verified by phone. Coordination with it: not yet arranged.",
    "Map pins: town centres geocoded by Nominatim at build.",
  ],
)
