# -*- coding: utf-8 -*-
PAGE = dict(
  slug="kosher-ski-holidays-french-alps",
  title="Kosher ski holidays in the French Alps, via Lyon",
  desc="Kosher ski in the French Alps: Chabad minyanim in Courchevel and Megève, kosher programs by resort, Shabbat on the mountain, and Lyon as your first stop.",
  h1="Kosher ski holidays in the French Alps", ital="where to pray, who to call, what to bring from Lyon",
  intro="A kosher ski week in France takes planning. In winter, Rabbi Daniel Belaïch runs Chabad services in Courchevel 1850 and Megève. For Alpe d'Huez, Les Deux Alpes, Serre Chevalier, Chamrousse and Val Thorens, the Beth Habad of Grenoble Alpes groups the families present into a minyan and brings a Sefer Torah: one mobile number, below. Private operators list kosher chalets and hotels in a dozen resorts. Supervision is rarely published, so you ask before you book. Lyon is the place to land, shop and stop for a few hours on the way up. We guide in Lyon only: we sell no ski package, no transport and no stay.",
  chips=["Minyanim: Courchevel, Megève, Grenoble side", "Kosher meals delivered in the resort", "Land and shop in Lyon", "Checked 8 October 2026"],
  illus="flat-stopover.png",
  crumb=("../jewish-lyon-guide/", "Jewish Lyon guide"),
  sections=[
    dict(type="text", h2="Where to find a minyan <i>in winter</i>",
      html="<p>Two resorts have a published Chabad service. Both are run by Rabbi Daniel Belaïch (habadalpes@yahoo.fr, 06 20 60 72 58).</p><ul><li><b>Courchevel 1850.</b> Services during the winter season, at 389 rue des Tovets. The rabbi writes that he helps with kosher needs, wine and challot for Shabbat, and with a Kaddish.</li><li><b>Megève.</b> Services in the 'Maison de la Montagne' room, according to the rabbi's own page. A second source gives 136 route Edmond de Rothschild. Write before you go: the venue has changed over the years.</li><li><b>Alpe d'Huez, Les Deux Alpes, Serre Chevalier, Chamrousse, Val Thorens, Les Menuires.</b> No standing service. The Beth Habad of Grenoble Alpes receives the calls from these resorts, groups the families present into a minyan and brings a Sefer Torah. Call Mendel Attal on the mobile below, and early.</li><li><b>Les Arcs, Tignes, Val d'Isère, La Plagne, Chamonix.</b> No Chabad or synagogue service published for winter. Private operators (below) organise a minyan when enough people come.</li></ul><p>The Chabad network of the Alps is headed by the Beth Habad of Grenoble, which also cooks and delivers kosher meals in the resorts: see <a href='../kosher-services-french-alps/'>kosher services in the Alps</a>.</p>"),
    dict(type="lieux", h2="Chabad <i>contacts</i>", items=[
      ("Synagogue at Hôtel Le Mont Charvin, Rabbi Daniel Belaïch", "389 rue des Tovets, 73120 Courchevel", "06 20 60 72 58", "Winter season. Wine and challot for Shabbat on request"),
      ("Chabad of the Alps in Megève, Rabbi Daniel Belaïch", "136 route Edmond de Rothschild, 74120 Megève", "06 20 60 72 58", "Winter. habadalpes@yahoo.fr. Venue: confirm before you come"),
      ("Beth Habad de Grenoble Alpes, Mendel Attal", "10 rue Lazare Carnot, 38000 Grenoble", "+33 7 81 82 31 93", "Alpe d'Huez, Les Deux Alpes, Serre Chevalier, Chamrousse, Val Thorens. Call the mobile, not the office line. Under Rabbi Yhia Lahiany, head of the Chabad network of the Alps"),
    ], source="Sources: synalpes.wordpress.com (Courchevel and Megève), Beth Habad de Grenoble Alpes (8 October 2026), chabad.org. Call before you go."),
    dict(type="beige", h2="Kosher ski programs <i>listed by resort</i>",
      html="<p>The directory skikosher.com lists these programs in France for the 2026/27 season. It states that its entries are not verified unless marked so. Supervision, menus and prices are not on the listings we read: ask each operator who supervises the kitchen before you pay.</p><ul><li><b>Val Thorens and Orelle (Trois Vallées):</b> Snow Riders apartments, 3 to 10 December 2026; Snow Riders Orelle, 17 to 22 January 2027; Stoliski Orelle, winter 2026/27. Orelle is the valley below Val Thorens.</li><li><b>Les Arcs 2000:</b> Chalet Albarelle, 17 to 21 and 21 to 28 January 2027.</li><li><b>Tignes:</b> Snow Riders Tignes Village Montana, 3 to 10 December 2026.</li><li><b>Morzine (Portes du Soleil):</b> Chalet Morzine, 10 to 17 and 17 to 22 January 2027.</li><li><b>Avoriaz (Portes du Soleil):</b> L'Amara, 2027 season.</li><li><b>La Toussuire (Les Sybelles):</b> Hotel Club J, ski season.</li><li><b>Montgenèvre:</b> MMV, January 2027.</li></ul><p>We do not recommend, rate or rank these operators. They are listed because a named source lists them. Source: skikosher.com, read on 7 October 2026.</p>"),
    dict(type="text", h2="Shabbat on <i>the mountain</i>",
      html="<p>Candle lighting in the Alps is not the Lyon time, and it changes every week. Look it up for your resort with Hebcal, and ask your Chabad contact for the service times.</p><ul><li><b>Plan the week around it.</b> Lifts and skiing are not part of Shabbat for an observant family. Choose a chalet or hotel close to your minyan, so you can walk.</li><li><b>Ask the property three questions.</b> Is there a Shabbat key or a door that opens without a card? Are lights and heating on a timer? Can food be kept warm before Shabbat?</li><li><b>Cook before it starts.</b> Prepare the Friday meal on Thursday or Friday morning, and carry the food up with you.</li><li><b>Know your nearest minyan.</b> Write it down before you leave Lyon: mobile networks drop in the valleys.</li></ul><p>For halakhic questions, ask your own rabbi. We give practical points only. See also <a href='../shabbat-in-lyon/'>Shabbat in Lyon</a>.</p>"),
    dict(type="text", h2="Kosher food <i>in the resort</i>",
      html="<p>There is no kosher shop in the resorts. Meals, though, can come to you: the kosher team of the Beth Habad of Grenoble Alpes delivers to a group for the week, or puts a chef in your chalet. <a href='../kosher-services-french-alps/'>Send us the request</a>. Otherwise bring your food from Lyon: the shops are on our page <a href='../lyon-gateway-to-the-alps-kosher/'>Lyon, the gateway to the Alps</a>. The Courchevel rabbi offers help with wine and challot. The operators above provide meals in their own programs: ask who supervises.</p><p>Private chefs advertise 'glatt kosher' cooking in Megève, Chamonix and Courchevel. Their supervision is not stated on their websites, so we do not list them as kosher hotels. Ask for the certificate.</p>"),
    dict(type="steps", h2="From Lyon to <i>your resort</i>", items=[
      ("Land in Lyon", "Lyon-Saint-Exupéry is two to three hours from most Savoie resorts. Drive times for 13 resorts are on our <a href='../lyon-gateway-to-the-alps-kosher/'>gateway page</a>."),
      ("Shop kosher", "Buy meat, bread and dairy at Hypercacher, Lilly Market or the butchers. Pack a cooler bag."),
      ("Take our 3 hour Stopover", "Your own transport waits while we guide you in Vieux Lyon and inside the Grande Synagogue. 390 € per group of 1 to 5 people. See the <a href='../tours/stopover/'>Stopover tour</a>."),
      ("Drive up", "Your driver takes you to the resort. We never guide on Shabbat or on Jewish holidays."),
    ]),
    dict(type="text", h2="Safety, <i>without alarm</i>",
      html="<p>Most trips pass without incident. We cannot promise zero risk. Our advice is simple.</p><ul><li>Keep your plans to your group, and do not post your hotel or route in real time.</li><li>Choose your own level of visibility in public: some travellers wear a cap rather than a kippa outside.</li><li>Travel with a companion at night.</li><li>Tell us if you have concerns: we adapt. A professional escort is available on request on our tours, priced separately and quoted on demand.</li></ul><p>More in our <a href='../jewish-travel-lyon-faq/'>honest FAQ</a>.</p>"),
    dict(type="map", h2="The resorts <i>on the map</i>", points=[
      ("Lyon-Saint-Exupéry airport", "Aéroport Lyon-Saint-Exupéry, 69125 Colombier-Saugnieu"),
      ("Courchevel 1850", "Courchevel 1850, 73120 Saint-Bon-Tarentaise"),
      ("Megève", "Megève, 74120"),
      ("Val Thorens", "Val Thorens, 73440 Les Belleville"),
      ("Les Menuires", "Les Menuires, 73440 Les Belleville"),
      ("Les Arcs 2000", "Les Arcs 2000, 73700 Bourg-Saint-Maurice"),
      ("Tignes", "Tignes, 73320"),
      ("Morzine", "Morzine, 74110"),
      ("Grenoble, Beth Habad", "10 rue Lazare Carnot, 38000 Grenoble"),
    ], note="Town-level pins, not street addresses, except Grenoble.", h=440),
    dict(type="photos", items=[("stock/traboule-1.jpg", "A Renaissance gallery, rue Juiverie"), ("stock/stjean-5.jpg", "Rue Saint-Jean, Vieux Lyon"), ("stock/stjean-7.jpg", "Rue Saint-Jean, Vieux Lyon"), ("stock/rose-7.jpg", "Rue du Boeuf")]),
    dict(type="faq", h2="Kosher ski: <i>questions</i>", items=[
      ("Which French ski resorts have a kosher minyan?", "Courchevel 1850 and Megève have a Chabad service in winter, run by Rabbi Daniel Belaïch. On the Grenoble side, Alpe d'Huez, Les Deux Alpes, Serre Chevalier, Chamrousse and Val Thorens, the Beth Habad of Grenoble Alpes groups the families present into a minyan on request."),
      ("Are there kosher ski holiday operators in France?", "Skikosher.com lists programs in Val Thorens and Orelle, Les Arcs 2000, Tignes, Morzine, Avoriaz, La Toussuire and Montgenèvre for 2026/27. The site does not verify its entries, so ask who supervises."),
      ("Can we get kosher food delivered to the resort?", "Yes, through the kosher team of the Beth Habad of Grenoble Alpes: meals delivered to your group for the week, or a chef in your chalet. Send us your resort and dates and they quote. Otherwise bring your food from Lyon."),
      ("Do observant families ski on Shabbat?", "No. Lifts and skiing are not part of Shabbat for an observant family. Choose lodging near your minyan and cook before Shabbat. For a ruling, ask your own rabbi."),
      ("How do we fit Lyon into a ski week?", "Land in Lyon, shop kosher, take our 3 hour Stopover with the Grande Synagogue, then drive two to three hours to the resort."),
      ("Do you sell ski packages or transfers?", "No. We guide in Lyon. For kosher chalets, chefs and delivered meals we pass your request to the kosher team in the Alps, which quotes and contracts with you directly."),
    ]),
    dict(type="cta", txt="Skiing in the Alps this winter?", msg="Hello, we are going skiing in the Alps and would like the Stopover tour in Lyon. Resort: / Arrival time: / Onward departure time: / Number of people:"),
  ],
  related=[("../kosher-services-french-alps/", "Kosher services in the Alps"), ("../lyon-gateway-to-the-alps-kosher/", "Lyon, the gateway to the Alps"), ("../tours/stopover/", "Stopover tour, 3 hours"), ("../summer-in-the-alps-jewish-families/", "Summer in the Alps for Jewish families"), ("../jewish-life-around-lyon/", "Jewish life around Lyon"), ("../shabbat-in-lyon/", "Shabbat in Lyon")],
  source="Sources: synalpes.wordpress.com, habadgrenoblealpes.com, skikosher.com, chabad.org.",
  jsonld=None, ticket=True,
  VERIF=[
    "Grenoble side (Alpe d'Huez, Les Deux Alpes, Serre Chevalier, Chamrousse, Val Thorens, Les Menuires), minyan and Sefer Torah on request, meals delivered: voice messages from Mendel Attal, Beth Habad de Grenoble Alpes, 8 October 2026. Nothing published. Mobile given for publication.",
    "Courchevel and Megève services: synalpes.wordpress.com (fetched 7 October 2026) and jtropez.com listings, not verified by phone. Winter season only, dates not published.",
    "Megève venue contradictory: 'Maison de la Montagne' (synalpes page) against 136 route Edmond de Rothschild (second source, base factuelle). Page shows both. To confirm with the rabbi.",
    "Rabbi Belaïch phone 06 20 60 72 58: synalpes. The base factuelle also gives 06 29 47 39 80, not published here.",
    "Les Menuires Megillah reading: single mention on habadgrenoblealpes.com.",
    "Grenoble Beth Habad office lines 04 76 43 38 58 (chabad.org) and 04 85 02 84 47 (habadgrenoblealpes.com) replaced by Mendel Attal's mobile at his request (office not always staffed).",
    "skikosher.com programs, names and dates: secondary source, 'entries not verified unless stated', commercial operators cited (Snow Riders, Stoliski, Chalet Albarelle, Chalet Morzine, L'Amara, Hotel Club J, MMV Montgenèvre). No rating, no supervision published. Dates for 2026/27 to recheck before indexation.",
    "Private chefs 'glatt kosher' in Megève, Chamonix, Courchevel: twisteragencechefmegeve.fr and maisonmegeve.com via base factuelle, supervision not stated. Sites not named on the page.",
    "'No kosher shop in the resorts': absence of results, not proof.",
    "Shabbat practical points (lifts, key, timer, cook before): general observant practice, no psak, no source. 'Mobile networks drop in valleys': general remark.",
    "Safety advice: same as the Jewish travel FAQ (Lyon Capitale, Nov 2023). Escort priced separately: ETAT.md 08/09.",
    "Map pins: town centres geocoded by Nominatim at build, not street addresses.",
    "Hotels/Kosher Ski Club Megève (TripAdvisor) not published: existence not verified.",
  ],
)
