# -*- coding: utf-8 -*-
CATERERS = [
  ("Choch & Lenny", "15 rue Jean-Claude-Vivant, 69100 Villeurbanne", "07 83 99 39 59", ""),
  ("La Cerise sur le Gâteau", "41 rue Alexandre-Boutin, 69100 Villeurbanne", "04 26 18 33 11", "pastry"),
  ("Mazal Corinne", "3 rue Victor-Basch, 69100 Villeurbanne", "06 86 46 33 85", ""),
  ("Les Gourmandises de Maëlle", "94 rue Hippolyte-Kahn, 69100 Villeurbanne", "", ""),
  ("Philibert David", "300 rue Francis-de-Pressensé, 69100 Villeurbanne", "06 19 13 19 07", ""),
  ("Samuel Califa, Le Vôtre", "64 rue Docteur-Rollet, 69100 Villeurbanne", "04 72 51 31 84", ""),
  ("Deli Prestige", "254 rue Francis-de-Pressensé, 69100 Villeurbanne", "06 67 64 81 26", ""),
]
PAGE = dict(
  slug="kosher-shabbat-meals-catering-lyon",
  title="Kosher catering and Shabbat meals in Lyon",
  desc="Seven caterers certified by the Beth Din de Lyon, Chabad Shabbat meals and kosher groceries for a Shabbat in an apartment. How to order before you land.",
  h1="Kosher catering and Shabbat meals in Lyon", ital="who cooks, how to order",
  intro="Seven caterers on the official list of the Beth Din de Lyon cook for Shabbat, and Chabad houses host on request. Whether each caterer delivers to a hotel is not published, so you ask before you order. We help you write, and you pay the caterer directly.",
  chips=["7 caterers certified by the Beth Din de Lyon", "2 kosher groceries", "Order before Thursday", "Checked 7 October 2026"],
  illus="flat-kosher.png",
  crumb=("../jewish-lyon-guide/", "Jewish Lyon guide"),
  sections=[
    dict(type="lieux", h2="Caterers certified by the <i>Beth Din</i>", items=CATERERS,
      source="Source: official list of establishments certified by the Beth Din de Lyon, bethdin-lyon.fr and consistoireregionaldelyon.org, checked 8 September 2026. Menus, prices and delivery areas are not published: ask each caterer. All seven are in Villeurbanne."),
    dict(type="text", h2="Delivery to <i>your hotel</i>",
      html="<p>No caterer on the list publishes a delivery service to hotels or a delivery area. Ask each one: do you deliver to my hotel, on which day and at what hour, and what do you need from me? Tell the hotel that a delivery is coming, and ask whether it can keep the food until Friday afternoon.</p><p>Three places on the Beth Din list state take-away or delivery: La Darka (07 66 05 11 49), Planet Sandwich (06 22 87 74 24) and, on Deliveroo and Uber Eats, Mika Sushi. These are weekday options. Nothing is delivered on Shabbat.</p><p>Two restaurants on the list also work as caterers: O'Sidney (04 72 16 08 35) and La Casa Del Coco (06 50 10 65 75).</p>"),
    dict(type="photos", items=[("stock/rose-3.jpg", "A traboule courtyard"), ("stock/boeuf-2.jpg", "Rue du Boeuf"), ("stock/stjean-5.jpg", "Vieux Lyon shopfronts"), ("stock/juiverie-7.jpg", "Rue Juiverie")]),
    dict(type="steps", h2="How to <i>order</i>", items=[
      ("Write to us", "Send your dates, the number of people and your hotel or neighbourhood. Order before Thursday if you want a Shabbat meal."),
      ("We tell you who to ask", "We send you the caterers closest to you and the questions to put to them, from the official list. We do not know which caterer delivers where, so you confirm with each one."),
      ("You order and pay the caterer", "You place the order and pay the caterer directly. We take no commission and we do not handle the money."),
    ]),
    dict(type="beige", h2="Meals for <i>groups</i>",
      html="<p>Group size, menus and prices are not published by any caterer on the list. For a synagogue group, a heritage trip or a family reunion, send us the number of people and the dates. We put you in touch with the caterers, and your guide builds the tour around your meals.</p><p>We guide on foot and do not provide buses. Your own transport, or the transport booked by your group, takes you to the meeting point.</p>"),
    dict(type="text", h2="Shabbat meals with <i>Chabad</i>",
      html="<p>Lyon has four Chabad houses: Centre-Ville (10 rue Mulet), Lyon 6 (60 rue Crillon), Villeurbanne (295 rue Francis-de-Pressensé) and the campus house. No meal schedule is published online. Call the house nearest your hotel before Friday noon and say how many you are. See <a href='../chabad-lyon/'>Chabad in Lyon</a> for addresses and phones.</p>"),
    dict(type="beige", h2="Groceries for a Shabbat <i>in an apartment</i>",
      html="<p>Three groceries are certified by the Beth Din de Lyon: Hypercacher, 17 rue Claudius-Pionchon, 69003 Lyon (04 78 85 00 80), its new Hypercacher Garibaldi, 46 rue Garibaldi, 69006 Lyon, and Lilly Market, 140 rue Dedieu, 69100 Villeurbanne (04 78 03 24 79). Lilly Market has a second shop in Écully. Opening hours are not published: call, and buy on Thursday or Friday morning. Three butchers are also on the list: <a href='../kosher-restaurants-lyon/'>all kosher addresses in Lyon</a>.</p>"),
    dict(type="map", h2="Caterers and groceries on the <i>map</i>", points=[(n, a) for n, a, t, x in CATERERS] + [("Hypercacher", "17 rue Claudius-Pionchon, 69003 Lyon"), ("Hypercacher Garibaldi", "46 rue Garibaldi, 69006 Lyon"), ("Lilly Market", "140 rue Dedieu, 69100 Villeurbanne")], note="Seven caterers and two groceries. Tap a marker for directions."),
    dict(type="faq", h2="Shabbat meals: <i>questions</i>", items=[
      ("Who certifies the caterers?", "The Beth Din de Lyon, the rabbinical court of the Consistoire. The list is published on bethdin-lyon.fr. Call the Beth Din on 04 12 04 05 15 if you follow another standard."),
      ("Do caterers deliver to my hotel?", "No caterer on the list publishes a hotel delivery service. Ask each one when you order. We help you write the message."),
      ("When must I order for Shabbat?", "Before Thursday. No caterer publishes an order deadline, so write to us on Monday or Tuesday and we send you the list."),
      ("Do you cook or sell the meals?", "No. The caterer sells and you pay the caterer. We take no commission."),
      ("Can I celebrate a Shabbat dinner with a group?", "Yes, with advance notice. Group menus and prices are not published, so we ask the caterers for you once we know your dates and number of people."),
    ]),
    dict(type="cta", txt="Need a Shabbat meal or a minyan near your hotel?", msg="Hello, I need a kosher Shabbat meal in Lyon. Dates: / Hotel or neighbourhood: / Number of people:"),
  ],
  related=[("../shabbat-in-lyon/", "Shabbat in Lyon"), ("../kosher-restaurants-lyon/", "Kosher restaurants in Lyon"), ("../chabad-lyon/", "Chabad in Lyon"), ("../where-to-stay-lyon-jewish-travellers/", "Where to stay in Lyon")],
  source="Sources: bethdin-lyon.fr and consistoireregionaldelyon.org (official list), fr.chabad.org.",
  jsonld=None, ticket=True,
  VERIF=[
    "Hotel delivery: no caterer publishes it. Written 'ask each caterer, we help you order'.",
    "'Order before Thursday', 'write Monday or Tuesday': our advice, no caterer deadline published.",
    "Group meals: no group capacity or menu published. Written as 'we ask the caterers for you'. To confirm that Mishpacha Tours wants to take this intermediary role.",
    "'We take no commission, we do not handle the money': operator decision to confirm, not in ETAT.md.",
    "'We do not provide buses': follows 'no transport plus accommodation package in year 1'; the stopover offer includes a van on quote, check the wording.",
    "Chabad meals: no schedule published, call. Phones of the four houses come from fr.chabad.org and conflict with habadlyon.com for Lyon 6 (06 29 89 19 97 against 06 25 30 90 38).",
    "Beth Din phone 04 12 04 05 15: read on the existing kosher page (base factuelle). La Darka, Planet Sandwich, Mika Sushi, O'Sidney, La Casa Del Coco: Beth Din list, 8 September 2026.",
    "Opening hours of groceries: not published.",
    "Lilly Market Ecully: Beth Din list. Three butchers: Eric Farache, Maison William, L'Heritage.",
  ],
)
