# -*- coding: utf-8 -*-
PAGE = dict(
  slug="lyon-gateway-to-the-alps-kosher",
  title="Lyon, gateway to the Alps for Jewish travellers",
  desc="Flying to Lyon for a kosher ski week? Drive times to 13 resorts, airport shuttles, where to buy kosher food before you go up, and a 3 hour Jewish Lyon stopover.",
  h1="Lyon, the gateway to the Alps", ital="for the Jewish traveller on the way to the mountain",
  intro="Lyon-Saint-Exupéry airport is about 2 h 10 from Courchevel and 2 h 30 from Val Thorens without traffic. Certified kosher groceries and butchers are in Lyon and Villeurbanne, not at the airport. Most Jewish families who ski in the French Alps land in Lyon, then drive two to three hours to the resort. Lyon-Saint-Exupéry airport is close to the autoroute, the city has kosher shops that open before you climb, and a Grande Synagogue worth three hours of your day. This page gives the drive times, the shuttle options and the shopping list. We guide in Lyon only: we do not sell transfers or stays.",
  chips=["13 resorts, drive times", "Kosher shops before the mountain", "3 hour Stopover, 390 €", "Checked 7 October 2026"],
  illus="flat-stopover.png",
  crumb=("../jewish-lyon-guide/", "Jewish Lyon guide"),
  sections=[
    dict(type="text", h2="Why land <i>in Lyon</i>",
      html="<ul><li><b>The airport.</b> Lyon-Saint-Exupéry sits east of the city, with the autoroute network to Savoie and Haute-Savoie a short drive away. Altibus and Ben's Bus both run ski shuttles from it (see below).</li><li><b>The station.</b> Lyon Part-Dieu is the main train station of the city. If you come by rail, Part-Dieu is the point where you shop, rest or visit before the next leg.</li><li><b>The motorway.</b> The A43 leaves Lyon toward Chambéry and the Savoie valleys. The Tarentaise resorts (Courchevel, Méribel, Val Thorens, Les Arcs, La Plagne, Tignes, Val d'Isère) and Maurienne lie beyond it.</li><li><b>The community.</b> Lyon has certified kosher groceries, butchers and bakeries, a Beth Din and a Grande Synagogue. See <a href='../kosher-restaurants-lyon/'>kosher in Lyon</a> and <a href='../synagogues-lyon/'>synagogues</a>.</li></ul>"),
    dict(type="beige", h2="Drive times from the airport <i>to each resort</i>",
      html="<p>These are typical times, without traffic, from Lyon-Saint-Exupéry airport by road, as listed by the ski directory j2ski.com. On a Saturday in February, or in snow, add one hour or more. Another transfer company, Alps2Alps, gives longer figures for some resorts (Courchevel 2 h 40, Méribel 2 h 30), so treat every figure as a range and ask your driver.</p><ul><li><b>Chamonix:</b> 2 h</li><li><b>Méribel:</b> 2 h</li><li><b>Courchevel:</b> 2 h 10</li><li><b>Megève:</b> 2 h 10</li><li><b>Les Gets:</b> 2 h 10</li><li><b>Les 2 Alpes:</b> 2 h 10</li><li><b>Morzine:</b> 2 h 20</li><li><b>Alpe d'Huez:</b> 2 h 20</li><li><b>Val Thorens:</b> 2 h 30</li><li><b>Tignes:</b> 2 h 40</li><li><b>Val d'Isère:</b> 2 h 40</li><li><b>Les Menuires, Les Arcs, La Plagne:</b> not listed in that table. They sit in the same Tarentaise valleys as Courchevel and Val Thorens: ask your transfer company for the exact time.</li></ul><p>Source: j2ski.com, Lyon St-Exupéry airport transfers (times 'approximate and often significantly affected by weather and traffic'); alps2alps.com.</p>"),
    dict(type="text", h2="Shuttles and <i>private transfers</i>",
      html="<p>We do not sell transport. Here is what the airport and the operators publish.</p><ul><li><b>Altibus.</b> Direct line from the airport to Val d'Isère, Tignes and Sainte-Foy-Tarentaise, most routes to Val Thorens and Les Menuires. Connections at Moûtiers or Aime stations for Courchevel, Méribel, Saint-Martin-de-Belleville and La Plagne. Winter timetable from 11 December 2026 to 3 April 2027, Friday, Saturday and Sunday, fares from 55 € for an adult.</li><li><b>Ben's Bus.</b> Listed on the airport website for Val d'Isère, Tignes, Les 2 Alpes, Courchevel, Méribel, La Plagne and others. Pick-up at the bus station, Terminal 1. Season not published on the airport page.</li><li><b>Private vans and taxis.</b> Alps2Alps and Alpine Fleet are among the transfer companies the airport and ski directories list. We name no taxi company: ask for a quote, and ask for a child seat if you need one.</li></ul><p>A shared shuttle that runs on Saturday does not suit a family that keeps Shabbat. If you land on a Friday, leave a wide margin before candle lighting, or book a night in Lyon (see <a href='../shabbat-in-lyon/'>Shabbat in Lyon</a>).</p>"),
    dict(type="lieux", h2="Kosher shopping before <i>you go up</i>", items=[
      ("Hypercacher", "17 rue Claudius-Pionchon, 69003 Lyon", "04 78 85 00 80", "Grocery"),
      ("Hypercacher Garibaldi", "46 rue Garibaldi, 69006 Lyon", "", "Grocery, opened 2026"),
      ("Lilly Market", "140 rue Dedieu, 69100 Villeurbanne", "04 78 03 24 79", "Grocery"),
      ("Eric Farache", "28 rue Villeroy, 69003 Lyon", "04 78 60 13 25", "Butcher"),
      ("Maison William, Boucherie Dahan", "50 rue Tête-d'Or, 69006 Lyon", "04 78 24 10 10", "Butcher"),
    ], source="Source: list of the Beth Din de Lyon, consulted on 8 September 2026, same entries as our <a href='../kosher-restaurants-lyon/'>kosher guide</a>. Opening hours are not published: call first. Every shop closes early on Friday."),
    dict(type="text", h2="What to buy <i>and how to carry it</i>",
      html="<p>We found no kosher shop published in the resorts and no delivery service from Lyon or Geneva to a resort. Bring what you need from Lyon.</p><ul><li><b>Shop in Villeurbanne or the 3rd and 6th arrondissements.</b> The shops above are in town, not at the airport. Book your driver for the round.</li><li><b>Bring a cooler bag and ice packs.</b> Meat, fish and dairy travel two to three hours.</li><li><b>Ask the Chabad rabbi for wine and challot.</b> In Courchevel, the rabbi publishes that he helps with wine and challot for Shabbat. See <a href='../kosher-ski-holidays-french-alps/'>kosher ski holidays</a>.</li></ul>"),
    dict(type="steps", h2="A typical ski-week <i>arrival</i>", items=[
      ("Land at Lyon-Saint-Exupéry", "Choose a flight that lands before noon if you want to see the city. Send us your arrival time and your onward departure time."),
      ("Shop for kosher food", "Your driver takes you to Hypercacher, Lilly Market or the butchers on the list. You buy for the week."),
      ("The Stopover, 3 hours", "Your own transport drops you in Vieux Lyon. We guide you for three hours, including the inside of the Grande Synagogue on quai Tilsitt, subject to opening hours and security on the day. Your bags stay in the van."),
      ("Take the road", "The driver picks you up at the same spot and takes the A43 toward your resort. Count two to three hours."),
    ]),
    dict(type="beige", h2="The Stopover: <i>Jewish Lyon between the plane and the slopes</i>",
      html="<p>Three hours of private guiding in Vieux Lyon and inside the Grande Synagogue, which is closed to visitors outside the Heritage Days. Price: 390 € per group of 1 to 5 people, plus 35 € per person from the sixth to the tenth. Airport pick-up is possible on request, as a paid add-on on quote, and never included. See the <a href='../tours/stopover/'>Stopover tour</a>.</p>"),
    dict(type="text", h2="Shabbat in Lyon, <i>before or after the mountain</i>",
      html="<p>A family that arrives on a Thursday or Friday can keep Shabbat in Lyon and go up on Sunday. A family coming down on Thursday can sleep in Lyon before a Friday morning flight. We guide from Sunday to Friday morning, never on Shabbat or on Jewish holidays. See <a href='../shabbat-in-lyon/'>Shabbat in Lyon</a> and <a href='../where-to-stay-lyon-jewish-travellers/'>where to stay</a>.</p>"),
    dict(type="map", h2="Your Lyon stop <i>on the map</i>", points=[
      ("Lyon-Saint-Exupéry airport", "Aéroport Lyon-Saint-Exupéry, 69125 Colombier-Saugnieu"),
      ("Lyon Part-Dieu station", "5 place Charles-Béraudier, 69003 Lyon"),
      ("Hypercacher", "17 rue Claudius-Pionchon, 69003 Lyon"),
      ("Hypercacher Garibaldi", "46 rue Garibaldi, 69006 Lyon"),
      ("Lilly Market", "140 rue Dedieu, 69100 Villeurbanne"),
      ("Grande Synagogue, quai Tilsitt", "13 quai Tilsitt, 69002 Lyon"),
    ], note="Tap a marker for directions."),
    dict(type="photos", items=[("stock/traboule-1.jpg", "A Renaissance gallery, rue Juiverie"), ("c-synagogue-7.jpg", "The Grande Synagogue, quai Tilsitt"), ("stock/stjean-3.jpg", "Rue Saint-Jean, Vieux Lyon"), ("stock/boeuf-4.jpg", "Rue du Bœuf, Vieux Lyon")]),
    dict(type="faq", h2="Lyon and the Alps: <i>questions</i>", items=[
      ("How far is Lyon airport from Courchevel or Val Thorens?", "Typically 2 h 10 to Courchevel and 2 h 30 to Val Thorens without traffic, according to j2ski.com. Another transfer company lists 2 h 40 for Courchevel. Winter roads and Saturday traffic add time."),
      ("Can we buy kosher food in the resort?", "We found no published kosher shop in the resorts. Bring your food from Lyon, and write to the Chabad rabbi in Courchevel for wine and challot."),
      ("Is there a shuttle from the airport to the resorts?", "Yes. Altibus runs a winter line on Fridays, Saturdays and Sundays from 11 December 2026 to 3 April 2027, and Ben's Bus is listed at the airport. Check the operator's timetable before you book."),
      ("Can we visit Lyon between the flight and the resort?", "Yes. Our Stopover is three hours, with the Grande Synagogue included, for 390 € per group of 1 to 5 people. Your own driver waits or comes back for you."),
      ("Do you pick us up at the airport?", "Airport pick-up is available on request, as a paid add-on on quote. It is never included in the base price."),
      ("Can we keep Shabbat in Lyon and go up on Sunday?", "Yes. Choose a hotel within walking distance of a synagogue and order your meals before Thursday. See our Shabbat in Lyon page."),
    ]),
    dict(type="cta", txt="Landing in Lyon before the mountain?", msg="Hello, we land in Lyon on our way to the Alps and would like the Stopover tour. Arrival time: / Onward departure time: / Resort: / Number of people:"),
  ],
  related=[("../tours/stopover/", "Stopover tour, 3 hours"), ("../kosher-ski-holidays-french-alps/", "Kosher ski holidays in the French Alps"), ("../summer-in-the-alps-jewish-families/", "Summer in the Alps for Jewish families"), ("../shabbat-in-lyon/", "Shabbat in Lyon"), ("../jewish-life-around-lyon/", "Jewish life around Lyon")],
  source="Sources: j2ski.com and alps2alps.com (drive times), altibus.com and lyonaeroports.com (shuttles), Beth Din de Lyon (shops).",
  jsonld=None, ticket=True,
  VERIF=[
    "Drive times: secondary source j2ski.com (Lyon St-Exupéry transfer table), 'approximate'. Alps2Alps gives longer times for Courchevel (2 h 40) and Méribel (2 h 30). Not Google Maps or ViaMichelin: to replace by a ViaMichelin read, 'typical, without traffic'.",
    "Les Menuires, Les Arcs, La Plagne: no time in any table found, written 'not listed'.",
    "Altibus: direct and connection routes, dates 11 Dec 2026 to 3 Apr 2027, Friday to Sunday, fare from 55 €, read on altibus.com. Commercial operator, to confirm before publication.",
    "Ben's Bus: listed on lyonaeroports.com (resorts, pick-up 'bus station, Terminal 1'), season not published.",
    "Alps2Alps and Alpine Fleet named as transfer companies: sourced on lyonaeroports.com and skikosher.com, no endorsement, no rating.",
    "A43 toward Chambéry and the Savoie valleys, 'airport close to the autoroute': general geography, no source cited.",
    "'No kosher shop published in the resorts' and 'no delivery from Lyon or Geneva found': absence of results, not proof. To ask the Chabad rabbi.",
    "Shops: Beth Din list read on 8 September 2026 (see _build_pratique.py). Phones and hours to confirm. 'Closes early on Friday': operator instruction, hour not published.",
    "Courchevel rabbi helps with wine and challot: synalpes.wordpress.com, statement of the rabbi.",
    "Airport and Part-Dieu map addresses: standard postal addresses, geocoded by Nominatim at build.",
    "'Land before noon', 'cooler bag', 'count two to three hours' and the shuttle-on-Saturday remark: our advice and general halakhic common sense, no psak.",
  ],
)
