# -*- coding: utf-8 -*-
PAGE = dict(
  slug="mikveh-lyon",
  title="Mikveh in Lyon and Villeurbanne: addresses, contacts",
  desc="Eight mikvahs in Lyon and Villeurbanne with addresses and phones. Mikvah Haya Mouchka, 60 rue Crillon, is listed as open nightly. How to ask before you travel.",
  h1="Mikveh in Lyon", ital="addresses and who to call",
  intro="Lyon and Villeurbanne have several mikvahs. The only one with a published opening time is Mikvah Haya Mouchka, 60 rue Crillon in the 6th arrondissement, listed as open nightly. Call or write before you travel: appointment rules are not published for the others.",
  chips=["8 mikvahs listed", "Mikvah Haya Mouchka: open nightly", "Call before you travel", "Checked 7 October 2026"],
  illus="flat-jewish-lyon.png",
  crumb=("../jewish-lyon-guide/", "Jewish Lyon guide"),
  sections=[
    dict(type="text", h2="The mikvah <i>to start with</i>",
      html="<p><b>Mikvah Haya Mouchka</b>, 60 rue Crillon, 69006 Lyon. Attached to Beth Habad Lyon 6e, under the supervision of Rabbi Yoel Nemanow. Hours listed: open nightly. Contact person listed: Mme Nemanow, 06 06 53 67 63, mikvelyon@gmail.com. Website listed: mikvelyon.fr. The mikvah follows the Chabad custom and is listed with a bor al gabei bor and a bor geshamim below the immersion pool.</p><p>No online booking is published. Write or call with your dates, and say that you are travelling.</p>"),
    dict(type="lieux", h2="Mikvahs in Lyon and <i>Villeurbanne</i>", items=[
      ("Mikvah Haya Mouchka", "60 rue Crillon, 69006 Lyon", "06 06 53 67 63", "Chabad. Listed as open nightly."),
      ("Mikvah Neveh Chalom", "317 rue Duguesclin, 69007 Lyon", "04 78 58 18 74", "At the Sephardi synagogue. Hours: not published. Phone is the synagogue's."),
      ("Mikvah Chaare Tzedek", "18 rue Saint-Mathieu, 69008 Lyon", "04 78 00 72 50", "Hours: not published."),
      ("Mikvah Centre Rav Hida", "501 avenue de la Sauvegarde, 69009 Lyon", "04 78 35 14 44", "La Duchère. Hours: not published."),
      ("Mikvah La Fraternité", "4 rue Malherbe, 69100 Villeurbanne", "04 78 85 66 22", "Hours: not published."),
      ("Mikvah École Juive", "40 rue Alexandre-Boutin, 69100 Villeurbanne", "04 72 83 80 25", "Hours: not published."),
      ("Mikvah Yeshiva Pinto", "20 bis rue des Mûriers, 69100 Villeurbanne", "04 78 03 89 14", "Hours: not published."),
      ("Mikvah Saint-Fons", "17 rue Albert-Thomas, 69190 Saint-Fons", "04 78 67 39 78", "Outside Lyon. Hours: not published."),
    ], source="Source: mikvah.org directory, Lyon and Villeurbanne listings, read on 7 October 2026. The directory says its listings are updated by the community. The Consistoire régional de Lyon states that it maintains the community's mikvahs (consistoireregionaldelyon.org)."),
    dict(type="map", h2="The mikvahs on the <i>map</i>", points=[
      ("Mikvah Haya Mouchka", "60 rue Crillon, 69006 Lyon"),
      ("Mikvah Neveh Chalom", "317 rue Duguesclin, 69007 Lyon"),
      ("Mikvah Chaare Tzedek", "18 rue Saint-Mathieu, 69008 Lyon"),
      ("Mikvah La Fraternité", "4 rue Malherbe, 69100 Villeurbanne"),
      ("Mikvah École Juive", "40 rue Alexandre-Boutin, 69100 Villeurbanne"),
      ("Mikvah Yeshiva Pinto", "20 bis rue des Mûriers, 69100 Villeurbanne"),
    ], note="Six mikvahs of Lyon and Villeurbanne. Tap a marker for directions."),
    dict(type="photos", items=[("stock/rose-7.jpg", "Presqu'île, rue Thomassin area"), ("stock/stjean-6.jpg", "Vieux Lyon"), ("stock/juiverie-6.jpg", "Rue Juiverie"), ("c-synagogue-4.jpg", "The carved door, Grande Synagogue")]),
    dict(type="steps", h2="How to <i>ask</i>", items=[
      ("Choose one", "Pick the mikvah nearest your hotel. Mikvah Haya Mouchka is about 35 minutes on foot from Tilsitt, so on Shabbat choose one within walking distance of where you sleep."),
      ("Write or call early", "Give your dates and say that you are travelling. Appointment rules, fees and the rules for men are not published for any of them."),
      ("Ask us if you need help", "We can tell you which mikvah is closest to your hotel and help you write the message. We do not book the appointment."),
    ]),
    dict(type="faq", h2="Mikveh in Lyon: <i>questions</i>", items=[
      ("Is there a mikvah open at night in Lyon?", "Mikvah Haya Mouchka, 60 rue Crillon, is listed as open nightly on mikvah.org. Confirm by phone or email before you go."),
      ("Can I book online?", "No online booking is published. The listing gives a phone number, mikvelyon@gmail.com and the website mikvelyon.fr."),
      ("Is there a mikvah for men?", "Not published. The directory does not say whether men may use each mikvah, so ask when you call."),
      ("What does it cost?", "Not published. Ask when you call."),
      ("Which mikvah is closest to the Grande Synagogue?", "Mikvah Haya Mouchka and Mikvah Neveh Chalom are the closest listed. We estimate 35 and 30 minutes on foot from Tilsitt. Check on a route planner."),
    ]),
    dict(type="cta", txt="Need help finding a mikvah near your hotel?", msg="Hello, I am looking for a mikvah in Lyon. Dates: / Hotel or neighbourhood:"),
  ],
  related=[("../shabbat-in-lyon/", "Shabbat in Lyon"), ("../chabad-lyon/", "Chabad in Lyon"), ("../synagogues-lyon/", "Synagogues in Lyon"), ("../jewish-travel-lyon-faq/", "Jewish travel to Lyon: the honest FAQ")],
  source="Sources: mikvah.org directory (Lyon and Villeurbanne), consistoireregionaldelyon.org.",
  jsonld=None, ticket=False,
  VERIF=[
    "Only source for the mikvahs: mikvah.org (Chabad-run directory, community-updated). Not confirmed by the Consistoire or by phone. Each address and phone to be called before indexing.",
    "Mikvah Haya Mouchka: address, phone 06 06 53 67 63, email, website mikvelyon.fr, 'open nightly' and Rabbi Yoel Nemanow from mikvah.org listing 1044. mikvelyon.fr could not be opened (SSL error): website not verified.",
    "The rabbi of Beth Habad Lyon 6e is 'Rabbi Yoel Nemanow' on mikvah.org and 'Rabbi Mendel Nemanow' on fr.chabad.org. Written with the mikvah.org name only on this page, to settle.",
    "Mikvah Centre Rav Hida: mikvah.org gives only 'La Sauvegarde, La Duchere'. Street address 501 avenue de la Sauvegarde comes from the synagogue list of habadlyon.com (base factuelle). Phone 04 78 35 14 44 from mikvah.org.",
    "Mikvah Neveh Chalom: no phone of its own, the synagogue's number is shown.",
    "The existing /chabad-lyon/ page says 'the community mikveh is in Villeurbanne, rue Francis-de-Pressensé'. The mikvah.org directory lists no mikvah at that street (Villeurbanne: La Fraternité, École Juive, Yeshiva Pinto). The page needs correction.",
    "Walking estimates from Tilsitt (35 and 30 min): estimate from map coordinates, rounded to 5 minutes.",
    "ticket=False: page without the booking form, since it is a service page; set True if the operator wants the form.",
  ],
)
