# -*- coding: utf-8 -*-
PAGE = dict(
  slug="shabbat-in-lyon",
  title="Shabbat in Lyon: synagogues, meals, where to stay",
  desc="Spending Shabbat in Lyon: where to pray, how to eat, where to sleep on foot, what closes on Friday and what to ask before you go. Checked 7 October 2026.",
  h1="Shabbat in Lyon", ital="how to keep it, step by step",
  intro="You can keep Shabbat well in Lyon if you plan it before you land. The Grande Synagogue and Neveh Chalom hold services, Chabad houses host on request, and kosher caterers cook for the weekend. Settle three things before you arrive: where you sleep, who feeds you, and how you carry.",
  chips=["Candle lighting times below", "7 Chabad houses, 2 historic synagogues", "No public eruv published", "Checked 7 October 2026"],
  illus="line-shabbat.png",
  crumb=("../jewish-lyon-guide/", "Jewish Lyon guide"),
  sections=[
    dict(type="shabbat"),
    dict(type="beige", h2="Shabbat with a <i>family</i>",
      html="<p>You do not have to spend Shabbat in a hotel room. Send us your dates and how many you are, and we put you in touch with a Chabad family in Lyon or Villeurbanne for the Friday night meal and the Shabbat lunch. This is Chabad hospitality: no charge, and a donation to the house is customary.</p><p>If you would rather have a Shabbat organised for your group alone, with the meals, the walk to the synagogue and the candle-lighting times taken care of, we arrange it on quote.</p>"),
    dict(type="text", h2="Plan it in <i>four decisions</i>",
      html="<ul><li><b>Where you sleep.</b> Choose a hotel you can reach on foot from a synagogue. Walking estimates and the questions to ask are on our page <a href='../where-to-stay-lyon-jewish-travellers/'>where to stay in Lyon</a>.</li><li><b>Where you pray.</b> Pick the synagogue before you pick the hotel. Details below.</li><li><b>Who feeds you.</b> Order before Thursday. Our page on <a href='../kosher-shabbat-meals-catering-lyon/'>kosher catering and Shabbat meals</a> explains how.</li><li><b>How you arrive.</b> Land and settle in before candle lighting. Once Shabbat starts, the metro and taxis are off the table. See the <a href='../jewish-travel-lyon-faq/'>travel FAQ</a>.</li></ul>"),
    dict(type="lieux", h2="Where to <i>pray</i>", items=[
      ("Grande Synagogue de Lyon", "13 quai Tilsitt, 69002 Lyon", "04 78 37 13 43", "Consistorial rite. Weekday Shacharit 7:00, Sunday 8:00, Mincha and Arvit 18:30. Shabbat times: not published, call."),
      ("Neveh Chalom", "317 rue Duguesclin, 69007 Lyon", "04 78 58 18 74", "Sephardi rite. Shacharit 7:00 on weekdays and 8:30 on Shabbat. Mincha 19:00 on weekdays and 19:20 on Shabbat."),
      ("Beth Habad Centre-Ville", "10 rue Mulet, 69001 Lyon", "06 21 82 05 56", "Chabad house in the Presqu'île. Service times: not published, call."),
      ("Chabad Loubavitch Lyon 6", "60 rue Crillon, 69006 Lyon", "06 29 89 19 97", "Chabad house in the 6th arrondissement. Service times: not published, call."),
      ("Chabad Loubavitch Villeurbanne", "295 rue Francis-de-Pressensé, 69100 Villeurbanne", "04 78 89 08 32", "Beth-Menahem synagogue and yeshiva on the same street. Service times: not published, call."),
    ], source="Sources: consistoiredelyon.fr and nevehchalom.fr (times read on 8 September 2026, they change with the season), fr.chabad.org directory. Call before you go."),
    dict(type="text", h2="At the <i>door</i>",
      html="<p>French authorities keep security forces visible around Jewish sites, so expect a check at the entrance of a synagogue. Bring a photo ID and arrive a few minutes early. No visitor procedure is published, so tell the synagogue when you plan to come. More on the <a href='../synagogues-lyon/'>synagogues of Lyon</a> page.</p>"),
    dict(type="photos", items=[("c-synagogue-7.jpg", "The Grande Synagogue, quai Tilsitt"), ("synagogue-tilsitt-arche.jpg", "The holy ark, Tilsitt"), ("stock/stjean-2.jpg", "Vieux Lyon, across the Saône"), ("stock/rose-2.jpg", "A Vieux Lyon courtyard")]),
    dict(type="beige", h2="Shabbat <i>meals</i>",
      html="<p>We know of no hotel in Lyon that serves kosher meals. Plan your Shabbat meals before you arrive.</p><ul><li><b>Caterers.</b> Seven caterers are certified by the Beth Din de Lyon. Whether each one delivers to a hotel is not published: ask when you order. We help you choose and write. See <a href='../kosher-shabbat-meals-catering-lyon/'>kosher catering in Lyon</a>.</li><li><b>Chabad.</b> A Chabad house can host you for a meal. No meal schedule is published online: call before Friday noon and say how many you are. See <a href='../chabad-lyon/'>Chabad in Lyon</a>.</li><li><b>Apartment Shabbat.</b> Two groceries certified by the Beth Din, Hypercacher and Lilly Market, sell what you need. Buy on Thursday: shops close on Friday afternoon.</li><li><b>Order before Thursday.</b> Order deadlines are not published, so write to us on Monday or Tuesday.</li></ul>"),
    dict(type="text", h2="Where to <i>sleep</i>",
      html="<p>Walk to prayer, walk to your meal, walk back. The Presqu'île, around Bellecour, puts you about ten minutes from the Grande Synagogue. The 6th arrondissement is the neighbourhood of most kosher restaurants on the Lyon side, about thirty-five minutes from Tilsitt on foot. Villeurbanne is the centre of community life, far from the old town. Our page <a href='../where-to-stay-lyon-jewish-travellers/'>where to stay in Lyon</a> gives the estimates, the map and the questions to put to a hotel about keys, floors and doors.</p>"),
    dict(type="text", h2="What <i>closes</i> on Friday",
      html="<p>Every kosher restaurant, bakery, butcher and grocery on the Beth Din list closes for Shabbat on Friday afternoon. The exact closing hour is not published: assume early, and shop on Thursday or Friday morning. Hours after Shabbat are not published either. Call before you plan a Saturday night dinner.</p><p>The Jewish cemetery follows the same rhythm: open until 16:00 on Friday, closed on Saturday (see <a href='../jewish-cemetery-lyon/'>the cemetery page</a>).</p>"),
    dict(type="beige", h2="Eruv <i>and carrying</i>",
      html="<p>No public eruv is published for Lyon; plan accordingly. We found no mention of one on the Consistoire pages or in the community directories. If you rely on an eruv at home, ask the synagogue or your host before you carry anything outdoors on Shabbat.</p>"),
    dict(type="text", h2="Mikveh",
      html="<p>Lyon has several mikvahs. Mikvah Haya Mouchka, 60 rue Crillon (6th arrondissement), is listed as open nightly. Addresses, phones and how to ask are on our <a href='../mikveh-lyon/'>mikveh page</a>. The Consistoire also looks after the community's mikvahs: Maison du Consistoire, 04 12 04 05 10.</p>"),
    dict(type="text", h2="Havdalah and <i>Sunday</i>",
      html="<p>Shabbat ends at the Havdalah time shown in the box at the top of this page, from Hebcal for Lyon. Havdalah times at each synagogue are not published. The Grande Synagogue holds Shacharit on Sunday at 8:00.</p>"),
    dict(type="text", h2="Our tours and <i>Shabbat</i>",
      html="<p>We never guide on Shabbat or on Jewish holidays. Your guide keeps Shabbat herself. A Sunday morning tour is possible, and so is a Friday morning tour that ends well before candle lighting. See the <a href='../tours/jewish-lyon/'>Jewish Lyon tour</a>: 2 hours 30 minutes, private group, inside the Grande Synagogue.</p>"),
    dict(type="faq", h2="Shabbat in Lyon: <i>questions</i>", items=[
      ("When does Shabbat start in Lyon?", "The box at the top of this page shows candle lighting and Havdalah for this week, from Hebcal. For your dates, write to us and we send the exact times."),
      ("Can I find a minyan on Shabbat?", "Yes. The Grande Synagogue and Neveh Chalom hold services, and so do the Chabad houses and 25 neighbourhood minyanim. Tell us your hotel and we point you to the nearest one. Shabbat times are published for Neveh Chalom only: call the others."),
      ("Is there a kosher hotel in Lyon?", "We know of none. If you find one, tell us and we update this page. Meanwhile, choose a hotel within walking distance of a synagogue and order your meals in advance."),
      ("Is there an eruv in Lyon?", "No public eruv is published for Lyon; plan accordingly. Ask the synagogue or your host before you carry."),
      ("Will anyone feed me if I arrive late on Friday?", "Do not count on it. Write to a Chabad house or a caterer before Thursday. Caterers' order deadlines are not published."),
      ("Do you guide on Shabbat?", "Never. We guide from Sunday to Friday morning, and we do not run tours on Jewish holidays."),
    ]),
    dict(type="cta", txt="Need a Shabbat meal or a minyan near your hotel?", msg="Hello, I am coming to Lyon for Shabbat. Dates: / Hotel or neighbourhood: / Number of people:"),
  ],
  related=[("../where-to-stay-lyon-jewish-travellers/", "Where to stay in Lyon"), ("../kosher-shabbat-meals-catering-lyon/", "Kosher catering and Shabbat meals"), ("../synagogues-lyon/", "Synagogues in Lyon"), ("../chabad-lyon/", "Chabad in Lyon"), ("../mikveh-lyon/", "Mikveh in Lyon"), ("../jewish-travel-lyon-faq/", "Jewish travel to Lyon: the honest FAQ")],
  source="Sources: consistoiredelyon.fr, nevehchalom.fr, consistoireregionaldelyon.org, bethdin-lyon.fr, fr.chabad.org, mikvah.org, hebcal.com.",
  jsonld=None, ticket=True,
  VERIF=[
    "Shabbat prayer times of the Grande Synagogue and of the Chabad houses: not published, written 'call'.",
    "Tilsitt and Neveh Chalom times read on 8 September 2026 on the official sites (base factuelle); seasonal, to confirm by phone.",
    "Eruv: no source found (consistoireregionaldelyon.org, habadlyon.com, web search). Written 'No public eruv is published for Lyon; plan accordingly'. To confirm with the Consistoire.",
    "'No hotel serving kosher meals that we know of': no source lists one. To confirm with the Consistoire.",
    "Chabad Shabbat meals on request: general Chabad practice, no Lyon-specific page or schedule published. To confirm by calling each centre.",
    "'Write Monday or Tuesday' and 'order before Thursday': our advice, no caterer deadline published.",
    "'Everything closes Friday afternoon, exact hour not published': operator instruction, closing hours are not on the Beth Din list.",
    "Walking estimates (10 min Presqu'ile, 35 min 6th arrondissement): walking estimate from map coordinates, rounded to 5 minutes.",
    "Cemetery hours: lyon.fr via base factuelle 8 September 2026.",
    "Consistoire number 04 12 04 05 10 (Maison du Consistoire, 317 rue Duguesclin) read on consistoireregionaldelyon.org on 7 October 2026. The Tilsitt line 04 78 37 13 43 is different.",
    "'Security forces visible around Jewish sites, check at the entrance, bring ID': national instruction relayed by the press (base factuelle section 2) and our advice. No visitor procedure published by Tilsitt.",
  ],
)
