# -*- coding: utf-8 -*-
PAGE = dict(
  slug="summer-in-the-alps-jewish-families",
  title="Summer in the Alps for Jewish families, via Lyon",
  desc="Kosher summer in the French Alps: synagogues, mikveh and meals in Aix-les-Bains, Annecy and Grenoble, what is published for Chamonix, and Lyon as your base.",
  h1="Summer in the Alps for Jewish families", ital="lakes, hikes and a minyan within reach",
  intro="Summer in the Alps means lakes, walking and long evenings. For an observant family it also means working out where the minyan is, who feeds you on Shabbat and what is open. Three towns near Lyon have a published community: Aix-les-Bains, Annecy and Grenoble. In the high resorts, the Chabad services we found are winter only. We guide in Lyon only: no packages, no stays.",
  chips=["Aix-les-Bains, Annecy, Grenoble", "Mikveh and meals, sourced", "Lyon as a base", "Checked 7 October 2026"],
  illus="flat-ski.png",
  crumb=("../jewish-lyon-guide/", "Jewish Lyon guide"),
  sections=[
    dict(type="text", h2="Three towns with a <i>published community</i>",
      html="<ul><li><b>Aix-les-Bains</b>, on the lake of Le Bourget, 1 h 15 from Lyon by train. The community website ci-aixlesbains.fr lists synagogues and oratories, Shabbat and holiday times, a mikveh, groceries and butchers, restaurants and caterers. It also shows a family offering home-made meals for visitors. We could read the headings but not the addresses of the shops: ask the community office.</li><li><b>Annecy</b>, on its lake, 1 h 45 from Lyon by car. One community centre and synagogue, with a rabbinical delegate. The nearest Chabad house we found is in Annemasse, 40 minutes away.</li><li><b>Grenoble</b>, 1 h 15 from Lyon by train, at the foot of the Chartreuse and Vercors. Two synagogues and the Beth Habad that heads the Chabad network of the Alps. We publish no shop or restaurant for Grenoble: the sources we found were secondary and one listed place is marked closed.</li></ul>"),
    dict(type="lieux", h2="Where to <i>pray and ask</i>", items=[
      ("Communauté israélite d'Aix-les-Bains", "7 rue Paul Bonna, 73100 Aix-les-Bains", "04 79 35 28 08", "contact@ci-aixlesbains.fr. Mikveh listed at the same address on mikvah.org. Home-made meals for visitors: ask the community for the contact"),
      ("Centre communautaire israélite d'Annecy", "18 rue de Narvik, 74000 Annecy", "04 50 67 69 37", "Rabbinical delegate Nephtaly Suissa. Mikveh listed at the same address on mikvah.org"),
      ("Beth Habad d'Annemasse", "17 rue du Clos Fleury, 74100 Annemasse", "", "The nearest Chabad house to Annecy, near the Geneva border. Phone not published"),
      ("Synagogue Bar Yohaï (CIG)", "4 rue des Bains, 38000 Grenoble", "04 76 46 15 14", "Consistoire régional"),
      ("Grande Synagogue consistoriale (ACJG Rachi)", "11 rue André Maginot, 38000 Grenoble", "04 76 87 02 80", "Office open Monday and Thursday mornings"),
      ("Beth Habad de Grenoble, Rabbi Yhia Lahiany", "10 rue Lazare Carnot, 38000 Grenoble", "04 76 43 38 58", "Heads the Chabad network of the Alps: habadgrenoblealpes.com"),
      ("Synagogue de Chambéry", "9 impasse Chardonnet, 73000 Chambéry", "04 79 85 53 58", "On the road between Lyon and the Savoie valleys. Rite and rabbi not published"),
    ], source="Sources: consistoireregionaldelyon.org (Annecy, Chambéry, Grenoble), ci-aixlesbains.fr, mikvah.org, habadgrenoblealpes.com, Wikipedia (Annemasse). Not verified by phone: call before you go."),
    dict(type="beige", h2="High resorts in summer: <i>what is published</i>",
      html="<ul><li><b>Courchevel and Megève.</b> The Chabad services we found are published for the winter season only. Nothing says they run in summer. Write to Rabbi Daniel Belaïch (habadalpes@yahoo.fr) before you count on one.</li><li><b>Chamonix.</b> A US operator, Kosher Outdoor Adventures, advertises a week of multi-level hiking in the Swiss, French and Italian Alps from Chamonix, with glatt kosher chef-prepared meals, a daily minyan with a Sefer Torah and Shomer Shabbat observance. Its trips are designed for adults over 50, so they do not suit a family with children. Dates are on its website. Source: kosheroutdooradventures.com.</li><li><b>Evian and Lake Geneva.</b> We found no published Jewish address for Evian. Geneva has its own community, across the border.</li><li><b>Kosher summer hotels or centres in the French Alps.</b> We name none. The directory skikosher.com lists kosher properties for the summer season in other countries, and none in France that we could read.</li></ul>"),
    dict(type="text", h2="Hiking and Shabbat <i>in the mountains</i>",
      html="<p>Summer plans fail on small things. These points help.</p><ul><li><b>Choose where you sleep before the trail.</b> Stay within walking distance of the minyan, or of the host who feeds you.</li><li><b>Cook ahead.</b> Prepare the Friday meal and bring it, or order it before Thursday from the community. Few mountain villages have a kosher shop.</li><li><b>Check candle lighting.</b> Use Hebcal for your town. Summer candle lighting in Savoie is later than in winter, and a late hike ends on Friday afternoon at the latest.</li><li><b>Write down the nearest minyan.</b> Before you lose the network in the valley.</li><li><b>Carry water and a map.</b> Do not start a long route on Friday.</li></ul><p>For rulings, ask your own rabbi. We give practical points only.</p>"),
    dict(type="steps", h2="Lyon as <i>your base or your first stop</i>", items=[
      ("Land and shop in Lyon", "Buy meat, bread and dairy at Hypercacher, Lilly Market or the butchers. See <a href='../lyon-gateway-to-the-alps-kosher/'>Lyon, the gateway to the Alps</a>."),
      ("Take a Lyon tour", "The <a href='../tours/jewish-lyon/'>Jewish Lyon tour</a> lasts 2 h 30, with the inside of the Grande Synagogue. The <a href='../tours/stopover/'>Stopover</a> lasts 3 hours, for families who drive on the same day."),
      ("Add Izieu", "The <a href='../tours/izieu/'>Maison d'Izieu</a> day trip leaves from Lyon. Izieu is in the Ain, east of Lyon, in the direction of Savoie. Price from 990 €, on quote."),
      ("Go up, come back", "Lyon works as a base for day trips by train to Grenoble, Aix-les-Bains and Chambéry. Spend Shabbat in Lyon: see <a href='../shabbat-in-lyon/'>Shabbat in Lyon</a>."),
    ]),
    dict(type="map", h2="The towns <i>on the map</i>", points=[
      ("Communauté israélite d'Aix-les-Bains", "7 rue Paul Bonna, 73100 Aix-les-Bains"),
      ("Annecy, centre communautaire", "18 rue de Narvik, 74000 Annecy"),
      ("Beth Habad d'Annemasse", "17 rue du Clos Fleury, 74100 Annemasse"),
      ("Beth Habad de Grenoble", "10 rue Lazare Carnot, 38000 Grenoble"),
      ("Synagogue de Chambéry", "9 impasse Chardonnet, 73000 Chambéry"),
      ("Grande Synagogue, Lyon", "13 quai Tilsitt, 69002 Lyon"),
    ], note="Tap a marker for directions.", h=440),
    dict(type="photos", items=[("stock/izieu-2.jpg", "Maison d'Izieu, the staircase"), ("c-izieu-8.jpg", "The Maison d'Izieu"), ("stock/boeuf-8.jpg", "Rue du Bœuf, Vieux Lyon"), ("stock/stjean-2.jpg", "Rue Saint-Jean, Vieux Lyon")]),
    dict(type="faq", h2="Summer in the Alps: <i>questions</i>", items=[
      ("Which Alpine town has the best-equipped Jewish community near Lyon?", "Aix-les-Bains is the most documented: synagogues, a mikveh, shops, restaurants and caterers are all announced on its community website, and a family offers home-made meals for visitors."),
      ("Is there a Chabad house in Annecy?", "We found none in Annecy itself. The Beth Habad of Annemasse, 40 minutes away, is the nearest. The Annecy community centre has a rabbinical delegate."),
      ("Do the Chabad services of Courchevel and Megève run in summer?", "The services we found are published for winter only. Write to Rabbi Belaïch before you plan around one."),
      ("Are there kosher hotels in the French Alps in summer?", "We name none, because we found no source. The skikosher.com directory does not show a French summer property that we could read."),
      ("Can we keep Shabbat while hiking?", "Plan lodging near a minyan, cook before Shabbat and finish your walk well before candle lighting. For a ruling, ask your rabbi."),
      ("Can we combine Lyon with the Alps?", "Yes. Land in Lyon, take a 2 h 30 city tour or the 3 hour Stopover, and add Izieu. Grenoble and Aix-les-Bains are about 1 h 15 from Lyon by train, Chambéry 1 h 20."),
    ]),
    dict(type="cta", txt="Summer trip through Lyon?", msg="Hello, we are travelling to the Alps this summer through Lyon and would like a tour. Dates: / Number of people: / Language:"),
  ],
  related=[("../kosher-services-french-alps/", "Kosher services in the Alps"), ("../lyon-gateway-to-the-alps-kosher/", "Lyon, the gateway to the Alps"), ("../kosher-ski-holidays-french-alps/", "Kosher ski holidays in the French Alps"), ("../tours/izieu/", "Maison d'Izieu day trip"), ("../jewish-life-around-lyon/", "Jewish life around Lyon"), ("../shabbat-in-lyon/", "Shabbat in Lyon")],
  source="Sources: ci-aixlesbains.fr, consistoireregionaldelyon.org, habadgrenoblealpes.com, mikvah.org, synalpes.wordpress.com, kosheroutdooradventures.com, skikosher.com.",
  wa="33652092301",
  jsonld=None, ticket=True,
  VERIF=[
    "Aix-les-Bains: ci-aixlesbains.fr homepage read 7 October 2026. Headings seen (synagogues, times, mikveh, groceries and butchers, restaurants, caterers), sub-pages NOT read: no shop address published here. Mikveh at 7 rue Paul Bonna: mikvah.org (secondary, spelled 'Bona').",
    "Home-made meals by 'la famille Cohen' 04 79 34 92 52 / 06 14 50 59 75: shown on the community homepage. Private family phones: the operator decides whether to publish.",
    "Annecy mikveh at 18 rue de Narvik: mikvah.org (secondary), not on the Consistoire page.",
    "Annemasse Beth Habad: Wikipedia, phone not published; 'nearest to Annecy, 40 minutes' repeated from /jewish-life-around-lyon/, estimate.",
    "Grenoble: addresses from the Consistoire and chabad.org (base factuelle). Commerces alloj.com excluded (secondary, one marked closed). Beth Habad phone 04 76 43 38 58 against 04 85 02 84 47 on habadgrenoblealpes.com: to confirm.",
    "Travel times 1 h 15 (Grenoble, Aix-les-Bains by train), 1 h 45 (Annecy by car): reused from /jewish-life-around-lyon/, not re-sourced today..",
    "Chabad Courchevel and Megève: winter only published (synalpes). No summer source found.",
    "Kosher Outdoor Adventures (Chamonix hiking): commercial operator, page read 7 October 2026, year of the dates not shown, adults 50+. No rating, no endorsement. To confirm the year before indexation.",
    "Evian and Lake Geneva: no source found, written 'no published Jewish address'. 'Geneva has its own community': general knowledge, not sourced.",
    "'No French summer property on skikosher.com': the page read lists winter 2026/27 entries; summer search not run.",
    "'Izieu east of Lyon, direction of Savoie': general geography. Izieu price 'from 990 €, on quote': ETAT.md. Chambéry synagogue 'on the road between Lyon and the Savoie valleys': general geography.",
    "Hiking and Shabbat points, 'summer candle lighting later': common sense, no psak, no source.",
  ],
)
