# -*- coding: utf-8 -*-
PAGE = dict(
  slug="where-to-stay-lyon-jewish-travellers",
  title="Where to stay in Lyon as a Jewish traveller: 3 areas",
  desc="Three areas to sleep in Lyon when you keep Shabbat: Presqu'île, 6th arrondissement, Villeurbanne. Walking estimates to Tilsitt and the questions to ask a hotel.",
  h1="Where to stay in Lyon", ital="for a Jewish traveller who keeps Shabbat",
  intro="Lyon has no kosher hotel that we know of. Observant visitors sleep within walking distance of a synagogue, about 10 minutes from the Grande Synagogue when they stay on the Presqu'île, and order Shabbat meals from a Beth Din-certified caterer before Thursday. Three areas work: the Presqu'île near the Grande Synagogue, the 6th arrondissement near the kosher restaurants, and Villeurbanne at the heart of community life.",
  chips=["3 areas compared", "Walking estimates to Tilsitt", "No kosher hotel that we know of", "Checked 7 October 2026"],
  illus="line-private.png",
  crumb=("../jewish-lyon-guide/", "Jewish Lyon guide"),
  sections=[
    dict(type="text", h2="The three areas, <i>on foot</i>",
      html="<p>All times are walking estimates to the Grande Synagogue, 13 quai Tilsitt, rounded to 5 minutes. Check your own route before you book.</p><ul><li><b>Presqu'île and Bellecour (Lyon 1st and 2nd).</b> About 10 minutes to Tilsitt. Rose and Roses, a dairy restaurant certified by the Beth Din, is at 21 rue Thomassin, and Neshama Kitchen, a meat restaurant, at 10 rue Mulet. Beth Habad Centre-Ville is also on rue Mulet. The best choice for a first Shabbat in Lyon.</li><li><b>Lyon 6th, Brotteaux and Foch.</b> About 35 minutes to Tilsitt. Most kosher restaurants on the Lyon side are here: Le Raphaelo, Comptoir 43, The Fifty and Five, Okami, plus a Chabad house on rue Crillon. A good choice if you pray at a local minyan and eat out.</li><li><b>Villeurbanne, Gratte-Ciel.</b> About 65 minutes to Tilsitt, so you will not walk there on Shabbat. This is the heart of community life: bakeries, groceries, caterers, a Chabad house and many neighbourhood synagogues within a few streets. Pick it if you pray locally and care little about the old town.</li></ul><p>Neveh Chalom, 317 rue Duguesclin in the 7th, is about 30 minutes on foot from Tilsitt. No kosher shop or restaurant on the official list is next to it.</p>"),
    dict(type="map", h2="The key places on the <i>map</i>", points=[
      ("Grande Synagogue de Lyon", "13 quai Tilsitt, 69002 Lyon"),
      ("Neveh Chalom", "317 rue Duguesclin, 69007 Lyon"),
      ("Hypercacher", "17 rue Claudius-Pionchon, 69003 Lyon"),
      ("Hypercacher Garibaldi", "46 rue Garibaldi, 69006 Lyon"),
      ("Le Raphaelo", "25 rue Sully, 69006 Lyon"),
      ("Comptoir 43", "43 rue Boileau, 69006 Lyon"),
      ("The Fifty and Five", "8 rue Professeur-Weill, 69006 Lyon"),
      ("Lilly Market", "140 rue Dedieu, 69100 Villeurbanne"),
    ], note="Synagogues, one grocery in the 3rd, three restaurants in the 6th and Lilly Market in Villeurbanne. Tap a marker for directions."),
    dict(type="photos", items=[("stock/stjean-4.jpg", "Vieux Lyon, a short walk from Tilsitt"), ("stock/boeuf-7.jpg", "Rue du Boeuf, Vieux Lyon"), ("stock/rose-6.jpg", "Pink Lyon facades"), ("c-juiverie-5.jpg", "Rue Juiverie")]),
    dict(type="beige", h2="Questions to ask <i>your hotel</i>",
      html="<p>We do not say what any hotel does. Put these questions to the hotel before you book, and keep the answers in writing.</p><ul><li>Is there a mechanical key, or can you give us one, instead of an electronic card?</li><li>Can we reach the room by stairs, and is a lower floor available?</li><li>Do any doors or lifts need a badge, and is a staff member available to open them on Shabbat?</li><li>Can you leave the room lights on a fixed setting, and is the key slot free of sensors?</li><li>Can we keep food in the room or in a fridge, and may we use a hot plate we bring ourselves?</li><li>Can you store food we order from a caterer and hand it over on Friday afternoon?</li><li>Can the front desk hold a bag until Saturday night if we need it?</li></ul>"),
    dict(type="text", h2="Kosher <i>hotels</i>",
      html="<p>Lyon has no kosher hotel that we know of. If you know one, tell us and we add it. Without one, plan your Shabbat meals before you arrive: see <a href='../kosher-shabbat-meals-catering-lyon/'>kosher catering and Shabbat meals in Lyon</a>.</p>"),
    dict(type="text", h2="Pair your stay with <i>your Shabbat</i>",
      html="<p>Pick the synagogue first, then the hotel. Prayer times and addresses are on our <a href='../shabbat-in-lyon/'>Shabbat in Lyon</a> page and on the <a href='../synagogues-lyon/'>synagogues of Lyon</a> page. Tell us where you sleep and we point you to the nearest minyan and the closest source of meals.</p>"),
    dict(type="faq", h2="Staying in Lyon: <i>questions</i>", items=[
      ("Which area is best for a first visit?", "The Presqu'île, around Bellecour. You are about ten minutes on foot from the Grande Synagogue and close to Vieux Lyon, where our tours begin."),
      ("Can I walk to the Grande Synagogue from Villeurbanne?", "We estimate about 65 minutes, so most visitors pray at a neighbourhood synagogue in Villeurbanne instead. We can point you to one."),
      ("Is there a kosher hotel in Lyon?", "We know of none. If you find one, tell us."),
      ("Can you book a hotel for me?", "No. We sell guiding only, and we do not book accommodation. We do help you choose an area and write your questions to the hotel."),
      ("Where do I buy food on Thursday?", "Hypercacher in the 3rd, Hypercacher Garibaldi in the 6th and Lilly Market in Villeurbanne are certified by the Beth Din de Lyon. All three are on the map above."),
    ]),
    dict(type="cta", txt="Need a Shabbat meal or a minyan near your hotel?", msg="Hello, I am planning a stay in Lyon. Dates: / Hotel or neighbourhood: / Number of people:"),
  ],
  related=[("../shabbat-in-lyon/", "Shabbat in Lyon"), ("../synagogues-lyon/", "Synagogues in Lyon"), ("../kosher-restaurants-lyon/", "Kosher restaurants in Lyon"), ("../jewish-travel-lyon-faq/", "Jewish travel to Lyon: the honest FAQ")],
  source="Sources: official list of the Beth Din de Lyon (bethdin-lyon.fr), consistoiredelyon.fr, nevehchalom.fr, fr.chabad.org. Map data from OpenStreetMap.",
  jsonld=None, ticket=True,
  VERIF=[
    "All walking times (10 min Presqu'ile, 35 min Lyon 6th, 65 min Villeurbanne, 30 min Neveh Chalom): walking estimate from map coordinates (straight line multiplied by 1.3, 5 km/h), rounded to 5 minutes. To check on a route planner.",
    "'We know of no kosher hotel in Lyon': two searches (hotel casher Lyon, kosher hotel Lyon) returned only a travel directory listing ordinary hotels, none certified. Not confirmed by the Consistoire.",
    "The hotel questions (key, floor, badge, lights, fridge) are our own advice, not claims about any hotel.",
    "'No kosher shop next to Neveh Chalom': deduced from addresses on the Beth Din list. To confirm on site.",
    "Neshama Kitchen: listed as a meat restaurant on the Beth Din list. Its link with a Chabad centre was not published and is not claimed.",
    "'We do not book accommodation': follows the fixed decision of 09/08 (no transport plus accommodation package in year 1).",
  ],
)
